export const Routes = {
  HOME: '/',
  FORM: '/form',
  TABLE: '/table',
  LIST: '/list',
  DATA: '/data',
  LOGIN: '/login',
  LISTING_SEARCH: '/search',
  LISTING: '/listing/:location',
  BOOKMARK: '/bookmark',
  DETAIL_LISTING: '/listing/detail/:id',
  DASHBOARD: '/dashboard',
  AGENTS: '/agents',
  MESSAGES: '/messages',
  SETTING: '/dashboard/setting',
  INVOICES: '/invoices',
  RESIDENTS: '/residents',
  USER_PROFILE: '/user/:id',
}
